### ISSUE TITLE
ERROR & EXIT: Execution failed in Profiling step.

### ISSUE THREAD

**Issue by mghanbari** [mocat2/mocat2#1]
I tried several times but still no success to pass the profiling step. Here is the last three lines of log file from profiling:
(20160926 17:38:10) : printing files for level=gene to /archive/MGH/mg-sample/MOCAT/TMP.SAMPLE_3.profiling.3samples_2016Sep26_173722.output
(20160926 17:38:11) : summarizing functional levels based on maps in /home/atmgh@GROUP.INTERNAL/app/MOCAT//data/3samples.padded.functional.map
Modification of a read-only value attempted at /home/atmgh@GROUP.INTERNAL/app/MOCAT/src/MOCATProfiling/Functional.pm line 51, <$MAP> line 2.

any idea how to fix this?

**Comment by mocat2** [comment]
Please repost this here:

https://sourceforge.net/p/mocat/tickets/

Also, please include a zipped version of your logs folder. Also, what is your Perl version? It may be that newer versions of Perl for some reason casts errors on things that worked in older versions.
